# NumPy Basics: Arrays and Operations

Welcome to the NumPy fundamentals workshop! NumPy (Numerical Python) is the foundation of scientific computing in Python. It provides fast, efficient array operations that are essential for data science and machine learning.

## Why NumPy?

- **Speed**: NumPy operations are implemented in C, making them much faster than pure Python
- **Memory Efficiency**: Arrays use less memory than Python lists
- **Vectorization**: Operations on entire arrays without explicit loops
- **Foundation**: Used by pandas, scikit-learn, TensorFlow, and more

In [2]:
# Import NumPy
import numpy as np

# Check version
print(f"NumPy version: {np.__version__}")

NumPy version: 2.4.0


## 1. Creating NumPy Arrays

NumPy arrays are homogeneous (all elements same type) and fixed-size, unlike Python lists.

In [ ]:
# From Python lists
list_1d = [1, 2, 3, 4, 5]
array_1d = np.array(list_1d)

print("1D Array:")
print(array_1d)
print(f"Shape: {array_1d.shape}")
print(f"Data type: {array_1d.dtype}")

1D Array:
[1 2 3 4 5]
Shape: (5,)
Data type: int64


In [ ]:
# 2D array (matrix)
array_2d = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]])

print("2D Array:")
print(array_2d)
print(f"Shape: {array_2d.shape}")
print(f"Number of dimensions: {array_2d.ndim}")
print(f"Data type: {array_2d.dtype}")

2D Array:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Shape: (3, 3)
Number of dimensions: 2
Data type: float64


### Array Creation Functions

NumPy provides many convenient functions to create arrays.

In [ ]:
# Array of zeros
zeros = np.zeros((3, 4))
print("Zeros (3x4):")
print(zeros)

# Array of ones
ones = np.ones((2, 3))
print("\nOnes (2x3):")
print(ones)

# Array with a constant value
filled = np.full((2, 2), 7)
print("\nFilled with 7 (2x2):")
print(filled)

Zeros (3x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones (2x3):
[[1. 1. 1.]
 [1. 1. 1.]]

Filled with 7 (2x2):
[[7 7]
 [7 7]]


In [5]:
# Identity matrix
identity = np.eye(4)
print("Identity matrix (4x4):")
print(identity)

# Range of values
range_array = np.arange(0, 10, 2)  # start, stop, step
print("\nRange (0 to 10, step 2):")
print(range_array)

# Evenly spaced values
linspace = np.linspace(0, 1, 5)  # start, stop, number of points
print("\nLinspace (5 points from 0 to 1):")
print(linspace)

Identity matrix (4x4):
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Range (0 to 10, step 2):
[0 2 4 6 8]

Linspace (5 points from 0 to 1):
[0.   0.25 0.5  0.75 1.  ]


In [6]:
# Random arrays
np.random.seed(42)  # For reproducibility

# Random values from uniform distribution [0, 1)
random_uniform = np.random.random((2, 3))
print("Random uniform [0, 1):")
print(random_uniform)

# Random integers
random_ints = np.random.randint(0, 100, size=(3, 3))
print("\nRandom integers [0, 100):")
print(random_ints)

# Random values from normal distribution
random_normal = np.random.randn(3, 3)  # mean=0, std=1
print("\nRandom normal (mean=0, std=1):")
print(random_normal)

Random uniform [0, 1):
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]

Random integers [0, 100):
[[74 74 87]
 [99 23  2]
 [21 52  1]]

Random normal (mean=0, std=1):
[[ 0.23309524  0.11799461  1.46237812]
 [ 1.53871497 -2.43910582  0.60344123]
 [-0.25104397 -0.16386712 -1.47632969]]


## 2. Array Indexing and Slicing

Access and modify array elements using indexing and slicing.

In [ ]:
# 1D indexing
arr = np.array([10, 20, 30, 40, 50])

print("Array:", arr)
print("First element:", arr[0])
print("Last element:", arr[-1])
print("First three elements:", arr[:3])
print("Every other element:", arr[::2])

Array: [10 20 30 40 50]
First element: 10
Last element: 50
First three elements: [10 20 30]
Every other element: [10 30 50]


In [ ]:
# 2D indexing
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

print("Matrix:")
print(matrix)
print("\nElement at row 1, col 2:", matrix[1, 2])
print("First row:", matrix[0, :])
print("Second column:", matrix[:, 1])
print("\nTop-left 2x2 submatrix:")
print(matrix[:2, :2])

Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Element at row 1, col 2: 7
First row: [1 2 3 4]
Second column: [ 2  6 10]

Top-left 2x2 submatrix:
[[1 2]
 [5 6]]


In [9]:
# Boolean indexing (masking)
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Create a boolean mask
mask = data > 5
print("Data:", data)
print("Mask (data > 5):", mask)
print("Values greater than 5:", data[mask])

# Can also do it in one line
print("Even values:", data[data % 2 == 0])

Data: [ 1  2  3  4  5  6  7  8  9 10]
Mask (data > 5): [False False False False False  True  True  True  True  True]
Values greater than 5: [ 6  7  8  9 10]
Even values: [ 2  4  6  8 10]


## 3. Array Operations

NumPy supports element-wise operations (vectorization) which are much faster than loops.

In [ ]:
# Basic arithmetic operations
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print("a:", a)
print("b:", b)
print("\nAddition (a + b):", a + b)
print("Subtraction (a - b):", a - b)
print("Multiplication (a * b):", a * b)
print("Division (b / a):", b / a)
print("Power (a ** 2):", a ** 2)

a: [1 2 3 4]
b: [10 20 30 40]

Addition (a + b): [11 22 33 44]
Subtraction (a - b): [ -9 -18 -27 -36]
Multiplication (a * b): [ 10  40  90 160]
Division (b / a): [10. 10. 10. 10.]
Power (a ** 2): [ 1  4  9 16]


In [ ]:
# Operations with scalars (broadcasting)
arr = np.array([1, 2, 3, 4, 5])

print("Array:", arr)
print("Array + 10:", arr + 10)
print("Array * 2:", arr * 2)
print("Array squared:", arr ** 2)

Array: [1 2 3 4 5]
Array + 10: [11 12 13 14 15]
Array * 2: [ 2  4  6  8 10]
Array squared: [ 1  4  9 16 25]


### Speed Comparison: NumPy vs Python Loops

In [ ]:
import time

# Create large arrays
size = 10**7
numpy_array = np.random.rand(size)
python_list = numpy_array.tolist()

# Python loop
start = time.time()
result_list = [x ** 2 for x in python_list]
python_time = time.time() - start

# NumPy vectorized
start = time.time()
result_numpy = numpy_array ** 2
numpy_time = time.time() - start

print(f"Python loop time: {python_time:.4f} seconds")
print(f"NumPy vectorized time: {numpy_time:.4f} seconds")
print(f"NumPy is {python_time/numpy_time:.1f}x faster!")

Python loop time: 0.6583 seconds
NumPy vectorized time: 0.0210 seconds
NumPy is 31.3x faster!


## 4. Aggregation Functions

Compute statistics and summaries of arrays.

In [ ]:
# Create sample data
np.random.seed(42)
data = np.random.randint(1, 100, size=20)

print("Data:", data)
print("\nSum:", np.sum(data))
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard deviation:", np.std(data))
print("Variance:", np.var(data))
print("Min:", np.min(data))
print("Max:", np.max(data))
print("Min index:", np.argmin(data))
print("Max index:", np.argmax(data))

Data: [52 93 15 72 61 21 83 87 75 75 88 24  3 22 53  2 88 30 38  2]

Sum: 984
Mean: 49.2
Median: 52.5
Standard deviation: 31.573089807619397
Variance: 996.8599999999999
Min: 2
Max: 93
Min index: 15
Max index: 1


In [ ]:
# Aggregations on 2D arrays
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Matrix:")
print(matrix)
print("\nSum of all elements:", np.sum(matrix))

# IMPORTANT: axis=0 refers to columns, axis=1 refers to rows
# We often specify which dimension of a multi-dimensional array to operate on
print("Sum along columns (axis=0):", np.sum(matrix, axis=0))
print("Sum along rows (axis=1):", np.sum(matrix, axis=1))

print("\nMean of each column:", np.mean(matrix, axis=0))
print("Mean of each row:", np.mean(matrix, axis=1))

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sum of all elements: 45
Sum along columns (axis=0): [12 15 18]
Sum along rows (axis=1): [ 6 15 24]

Mean of each column: [4. 5. 6.]
Mean of each row: [2. 5. 8.]


## 5. Array Manipulation

Reshape, stack, and split arrays.

In [ ]:
# Reshaping
arr = np.arange(12)
print("Original (shape {}):".format(arr.shape))
print(arr)

reshaped = arr.reshape(3, 4)
print("\nReshaped to 3x4:")
print(reshaped)

reshaped2 = arr.reshape(2, 6)
print("\nReshaped to 2x6:")
print(reshaped2)

# -1 means "infer this dimension"
reshaped3 = arr.reshape(4, -1)
print("\nReshaped to 4x? (inferred):")
print(reshaped3)

Original (shape (12,)):
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped to 3x4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped to 2x6:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Reshaped to 4x? (inferred):
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
# Flattening
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix:")
print(matrix)
print("\nFlattened:", matrix.flatten())
print("Also flattened:", matrix.ravel())

Matrix:
[[1 2 3]
 [4 5 6]]

Flattened: [1 2 3 4 5 6]
Also flattened: [1 2 3 4 5 6]


In [ ]:
# Transposing
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

print("Original (2x3):")
print(matrix)
print("\nTransposed (3x2):")
print(matrix.T)

Original (2x3):
[[1 2 3]
 [4 5 6]]

Transposed (3x2):
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Stacking arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a:", a)
print("b:", b)

# Vertical stack (rows)
vstacked = np.vstack([a, b])
print("\nVertical stack:")
print(vstacked)

# Horizontal stack (columns)
hstacked = np.hstack([a, b])
print("\nHorizontal stack:")
print(hstacked)

a: [1 2 3]
b: [4 5 6]

Vertical stack:
[[1 2 3]
 [4 5 6]]

Horizontal stack:
[1 2 3 4 5 6]


## 6. Broadcasting

Broadcasting allows NumPy to perform operations on arrays of different shapes.
Under the hood, NumPy duplicates the smaller array multiple times to match the shape of the larger array without actually copying data, which saves memory and computation time.

In [ ]:
# Broadcasting example 1: scalar to array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Array:")
print(arr)
print("\nArray + 10:")
print(arr + 10)  # 10 is broadcast to all elements

Array:
[[1 2 3]
 [4 5 6]]

Array + 10:
[[11 12 13]
 [14 15 16]]


In [ ]:
# Broadcasting example 2: 1D to 2D
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row = np.array([10, 20, 30])

print("Matrix (3x3):")
print(matrix)
print("\nRow (3,):")
print(row)
print("\nMatrix + row (broadcast):")
print(matrix + row)  # row is broadcast to each row of matrix

Matrix (3x3):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Row (3,):
[10 20 30]

Matrix + row (broadcast):
[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [ ]:
# Broadcasting example 3: column operation
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

col = np.array([[10],
                [20],
                [30]])

print("Matrix (3x3):")
print(matrix)
print("\nColumn (3x1):")
print(col)
print("\nMatrix * column (broadcast):")
print(matrix * col)  # col is broadcast to each column of matrix

Matrix (3x3):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Column (3x1):
[[10]
 [20]
 [30]]

Matrix + column (broadcast):
[[ 10  20  30]
 [ 80 100 120]
 [210 240 270]]


## 7. Mathematical Functions

NumPy provides many mathematical functions that operate element-wise.

In [ ]:
# Trigonometric functions
angles = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])

print("Angles (radians):", angles)
print("\nSine:", np.sin(angles))
print("Cosine:", np.cos(angles))
print("Tangent:", np.tan(angles))

Angles (radians): [0.         0.52359878 0.78539816 1.04719755 1.57079633]

Sine: [0.         0.5        0.70710678 0.8660254  1.        ]
Cosine: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
Tangent: [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [ ]:
# Exponential and logarithmic
x = np.array([1, 2, 3, 4, 5])

print("x:", x)
print("\nExponential (e^x):", np.exp(x))
print("Natural log (ln(x)):", np.log(x))
print("Log base 10:", np.log10(x))
print("Log base 2:", np.log2(x))

x: [1 2 3 4 5]

Exponential (e^x): [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Natural log (ln(x)): [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Log base 10: [0.         0.30103    0.47712125 0.60205999 0.69897   ]
Log base 2: [0.         1.         1.5849625  2.         2.32192809]


In [ ]:
# Other useful functions
data = np.array([-2.5, -1.3, 0, 1.7, 2.9])

print("Data:", data)
print("\nAbsolute value:", np.abs(data))
print("Square root (of positive values):", np.sqrt(np.abs(data)))
print("Round:", np.round(data))
print("Floor:", np.floor(data))
print("Ceiling:", np.ceil(data))

Data: [-2.5 -1.3  0.   1.7  2.9]

Absolute value: [2.5 1.3 0.  1.7 2.9]
Square root (of positive values): [1.58113883 1.14017543 0.         1.30384048 1.70293864]
Round: [-2. -1.  0.  2.  3.]
Floor: [-3. -2.  0.  1.  2.]
Ceiling: [-2. -1.  0.  2.  3.]


## 8. Linear Algebra Operations

Essential for machine learning!

In [ ]:
# Dot product (vector)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# You CANNOT use the * operator for dot product
dot_product = np.dot(a, b)
print("a:", a)
print("b:", b)
print("Dot product (a · b):", dot_product)
print("Verification: 1*4 + 2*5 + 3*6 =", 1*4 + 2*5 + 3*6)

a: [1 2 3]
b: [4 5 6]
Dot product (a · b): 32
Verification: 1*4 + 2*5 + 3*6 = 32


In [ ]:
# Matrix multiplication
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

# Matrix multiplication
C = np.matmul(A, B)  # or A @ B
print("\nA @ B:")
print(C)

# Element-wise multiplication (different!)
print("\nA * B (element-wise):")
print(A * B)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

A @ B:
[[19 22]
 [43 50]]

A * B (element-wise):
[[ 5 12]
 [21 32]]


In [ ]:
# Matrix-vector multiplication (important for ML!)
weights = np.array([[0.5, 0.3],
                    [0.2, 0.8],
                    [0.1, 0.9]])

inputs = np.array([2.0, 3.0])

print("Weights (3x2):")
print(weights)
print("\nInputs (2,):")
print(inputs)
print("\nOutput (weights @ inputs):")
output = weights @ inputs
print(output)
print(f"\nShape: {output.shape}")

Weights (3x2):
[[0.5 0.3]
 [0.2 0.8]
 [0.1 0.9]]

Inputs (2,):
[2. 3.]

Output (weights @ inputs):
[1.9 2.8 2.9]

Shape: (3,)


In [38]:
# Example of how NOT to broadcast to avoid errors
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

col = np.array([[10, 20]])  # Incorrect shape (1x2) instead of (1x3)

# This will raise an error
# print(matrix * col)

## 9. Practical Example: Normalizing Data

A common preprocessing step in machine learning is to normalize data (zero mean, unit variance).

In [36]:
# Generate sample data
np.random.seed(42)
data = np.random.randn(100) * 10 + 50  # mean=50, std=10

print("Original data statistics:")
print(f"Mean: {np.mean(data):.2f}")
print(f"Std: {np.std(data):.2f}")
print(f"Min: {np.min(data):.2f}")
print(f"Max: {np.max(data):.2f}")

# Standardization (z-score normalization)
normalized = (data - np.mean(data)) / np.std(data)

print("\nNormalized data statistics:")
print(f"Mean: {np.mean(normalized):.2f}")
print(f"Std: {np.std(normalized):.2f}")
print(f"Min: {np.min(normalized):.2f}")
print(f"Max: {np.max(normalized):.2f}")

Original data statistics:
Mean: 48.96
Std: 9.04
Min: 23.80
Max: 68.52

Normalized data statistics:
Mean: -0.00
Std: 1.00
Min: -2.78
Max: 2.16


## 10. Practice Exercise: Temperature Conversion

Let's practice what we've learned with a simple exercise.

In [4]:
# Temperature data in Fahrenheit
temps_f = np.array([32, 50, 68, 86, 104, 122, 140])

# Convert to Celsius using the formula: C = (F - 32) * 5/9
temps_c = (temps_f - 32) * 5 / 9

print("Fahrenheit:", temps_f)
print("Celsius:", temps_c)

# Find the mean temperature in both Fahrenheit and Celsius
mean_f = np.mean(temps_f)
mean_c = np.mean(temps_c)

print(f"\nMean temperature: {mean_f:.1f}°F = {mean_c:.1f}°C")

#  Find the number of days where temperature exceeds 30°C
hot_days = [1 for x in temps_c if x > 30]
print(f"\nDays with temp > 30°C: {np.sum(hot_days)}")

Fahrenheit: [ 32  50  68  86 104 122 140]
Celsius: [ 0. 10. 20. 30. 40. 50. 60.]

Mean temperature: 86.0°F = 30.0°C

Days with temp > 30°C: 3


## Summary

In this notebook, you learned:

1. **Creating arrays**: `np.array()`, `np.zeros()`, `np.ones()`, `np.random.random()`, etc.
2. **Indexing and slicing**: Access and modify array elements
3. **Vectorized operations**: Fast element-wise operations without loops
4. **Aggregations**: `sum()`, `mean()`, `std()`, `min()`, `max()`, etc.
5. **Array manipulation**: `reshape()`, `flatten()`, `transpose()`, `stack()`
6. **Broadcasting**: Operations on arrays of different shapes
7. **Mathematical functions**: `sin()`, `cos()`, `exp()`, `log()`, etc.
8. **Linear algebra**: Dot products and matrix multiplication

These fundamentals are essential for the next notebook, where we'll implement machine learning algorithms from scratch!

### Key Takeaways

- **Always use NumPy operations instead of Python loops** when possible
- **Broadcasting** makes code cleaner and faster
- **Vectorization** is the key to NumPy's speed
- NumPy is the foundation for pandas, scikit-learn, and deep learning frameworks